namespace Tankerkiller125.BicepExtensionGen.Generation;

/// <summary>
/// Provides the "this file is generated" banner for emitted files, using the comment syntax
/// appropriate to each file type. The C# banner uses the standard <c>// &lt;auto-generated&gt;</c>
/// marker that Roslyn analyzers, StyleCop, formatters, and coverage tools recognize to skip the file.
/// </summary>
public static class GeneratedHeader
{
    private const string Tool = "Tankerkiller125.BicepExtensionGen";
    private const string Note = "This file was generated from an OpenAPI document by " + Tool + ".";
    private const string Warn = "Manual edits will be overwritten the next time the extension is regenerated.";

    /// <summary>The banner to prepend for the given file, or empty string when none applies (e.g. JSON, Markdown).</summary>
    public static string For(string relativePath) => Path.GetExtension(relativePath).ToLowerInvariant() switch
    {
        ".cs" =>
            $"""
            // <auto-generated>
            //     {Note}
            //     {Warn}
            // </auto-generated>

            """,
        ".csproj" =>
            $"""
            <!--
              <auto-generated>
                {Note}
                {Warn}
              </auto-generated>
            -->

            """,
        ".ps1" =>
            $"""
            # <auto-generated>
            #     {Note}
            #     {Warn}
            # </auto-generated>

            """,
        _ => "",
    };
}
