namespace Tankerkiller125.BicepExtensionGen.Tests;

[TestClass]
public sealed class EmissionTests
{
    private static async Task<string> GenerateToTempAsync()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "petstore.yaml");
        var load = await OpenApiLoader.LoadAsync(path);
        var model = new ResourceModelBuilder(load.Document, "Contoso.PetStore", "0.1.0", MappingMode.Path).Build();

        var outDir = Path.Combine(Path.GetTempPath(), "bicepextgen-test-" + Guid.NewGuid().ToString("N"));
        new ExtensionWriter(outDir, "Contoso.PetStore").Write(model);
        return outDir;
    }

    [TestMethod]
    public async Task Emits_expected_project_files()
    {
        var dir = await GenerateToTempAsync();
        try
        {
            foreach (var relative in new[]
            {
                "src/contoso-pet-store.csproj",
                "src/Program.cs",
                "src/Models/Configuration.cs",
                "src/Models/Common.cs",
                "src/Models/Pet.cs",
                "src/Handlers/ResourceHandlerBase.cs",
                "src/Handlers/PetHandler.cs",
                ".config/dotnet-tools.json",
                "build.ps1",
                "README.md",
            })
            {
                Assert.IsTrue(File.Exists(Path.Combine(dir, relative)), $"Expected file missing: {relative}");
            }
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [TestMethod]
    public async Task Resource_model_has_docgen_and_bicep_attributes()
    {
        var dir = await GenerateToTempAsync();
        try
        {
            var pet = await File.ReadAllTextAsync(Path.Combine(dir, "src/Models/Pet.cs"));

            StringAssert.Contains(pet, "[ResourceType(\"Pet\")]");
            StringAssert.Contains(pet, "[BicepDocHeading(\"Pet\"");
            StringAssert.Contains(pet, "[BicepDocExample(");
            StringAssert.Contains(pet, "ObjectTypePropertyFlags.Identifier | ObjectTypePropertyFlags.Required");
            StringAssert.Contains(pet, "public required long Id");
            StringAssert.Contains(pet, "public PetStatus? Status");
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [TestMethod]
    public async Task Generated_files_carry_an_auto_generated_header()
    {
        var dir = await GenerateToTempAsync();
        try
        {
            // C# files must start with the marker Roslyn/analyzers/coverage recognize.
            foreach (var cs in new[] { "src/Program.cs", "src/Models/Pet.cs", "src/Handlers/PetHandler.cs", "src/Models/Configuration.cs" })
            {
                var text = await File.ReadAllTextAsync(Path.Combine(dir, cs));
                Assert.IsTrue(text.StartsWith("// <auto-generated>", StringComparison.Ordinal), $"{cs} missing C# header");
            }

            // The project and scripts get a banner in their own comment syntax.
            var csproj = await File.ReadAllTextAsync(Path.Combine(dir, "src/contoso-pet-store.csproj"));
            StringAssert.StartsWith(csproj, "<!--");
            StringAssert.Contains(csproj, "<auto-generated>");

            var script = await File.ReadAllTextAsync(Path.Combine(dir, "build.ps1"));
            StringAssert.StartsWith(script, "# <auto-generated>");
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [TestMethod]
    public async Task Readme_puts_project_usage_before_api_docs_with_auth_guidance()
    {
        var dir = await GenerateToTempAsync();
        try
        {
            var readme = await File.ReadAllTextAsync(Path.Combine(dir, "README.md"));

            // Project usage comes first; OpenAPI-derived content comes after.
            var projectIdx = readme.IndexOf("## Working with this project", StringComparison.Ordinal);
            var apiIdx = readme.IndexOf("## Using the extension", StringComparison.Ordinal);
            Assert.IsTrue(projectIdx >= 0, "Missing project usage section.");
            Assert.IsTrue(apiIdx > projectIdx, "API docs must come after project usage.");

            // Auth guidance is specific to the detected scheme (apiKey in the X-API-Key header).
            StringAssert.Contains(readme, "sent in the `X-API-Key` request header");

            // Quick start is copy-paste valid: secure parameter + extension block.
            StringAssert.Contains(readme, "@secure()");
            StringAssert.Contains(readme, "extension contosoPetStore with {");
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [TestMethod]
    public async Task Handler_wires_crud_paths()
    {
        var dir = await GenerateToTempAsync();
        try
        {
            var handler = await File.ReadAllTextAsync(Path.Combine(dir, "src/Handlers/PetHandler.cs"));

            StringAssert.Contains(handler, "HttpMethod.Get, $\"pets/{Uri.EscapeDataString(props.Id.ToString()!)}\"");
            StringAssert.Contains(handler, "HttpMethod.Post, $\"pets\"");
            StringAssert.Contains(handler, "HttpMethod.Put, $\"pets/{Uri.EscapeDataString(props.Id.ToString()!)}\"");
            StringAssert.Contains(handler, "props.CreatedAt = latest.CreatedAt;");
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }
}
